Repository BrainPad/cliboa, pull requests merged in 2025-08, with the labels that each got.

#480 #479 Drop old Python support to work CI, and modernize module management. (due 2025/08/31)
  .github/workflows/test-functional.yaml
  .github/workflows/test-static.yaml
  .github/workflows/test.yaml
  .gitignore
  .importlinter
  README.md
  cliboa/adapter/csv.py
  cliboa/adapter/file.py
  cliboa/cli/cliboadmin.py
  cliboa/core/worker.py
  cliboa/scenario/transform/csv.py
  cliboa/scenario/transform/file.py
  cliboa/scenario/transform/json.py
  cliboa/template/Pipfile.above310
  cliboa/template/Pipfile.above37
  cliboa/template/Pipfile.above38
  cliboa/template/Pipfile.above39
  cliboa/template/pyproject.above310.toml
  cliboa/template/pyproject.above37.toml
  cliboa/template/pyproject.above38.toml
  cliboa/template/pyproject.above39.toml
  cliboa/test/__init__.py
  cliboa/test/adapter/test_http.py
  cliboa/test/core/test_listener.py
  cliboa/test/core/test_manager.py
  cliboa/test/scenario/transform/test_file.py
  cliboa/test/util/test_lisboa_log.py
  pyproject.toml
  setup.cfg
  setup.py
  tools/script/init_dev.py
  tools/script/lint.sh
Labels: bug, refactoring

#484 #483 Add rule to delete merged branches and set up CI check. (due 2025/09/30)
  .github/workflows/check_merged_branches.yaml
  CONTRIBUTING.md
Labels: maintenance

#494 Implement CsvSplitRows class. (fixes #493, due 2025/08/29)
  cliboa/scenario/transform/csv.py
  cliboa/test/scenario/transform/test_csv.py
  docs/modules/csv_split.md
Labels: enhancement

#496 fix: resolve import-linter violations and remove dead code
  cliboa/adapter/http.py
  cliboa/core/validator.py
  cliboa/scenario/load/gcp.py
  cliboa/scenario/load/sftp.py
  cliboa/scenario/rdbms.py
  cliboa/scenario/transform/aes.py
  cliboa/scenario/transform/csv.py
  cliboa/scenario/transform/file.py
  cliboa/scenario/transform/gpg.py
  cliboa/scenario/transform/json.py
  cliboa/scenario/transform/system.py
  cliboa/test/adapter/test_http.py
Labels: bug, refactoring

#497 Update CsvRowDelete documentation to accurately reflect filtering behavior
  docs/modules/csv_row_delete.md
Labels: documentation
